---
name: star
friction: 0
maxXSpeed: -1
maxYSpeed: -1
gravitous: true
collidable: true
sprite: spr_star
xScale: 1
yScale: 1
animationSpeed: 0
depth: 0
attributes:
  {}
triggers:
  - type: Collision
    target: player
    actions:
      - type: AttributeChange
        conditionals:
          []
        attribute: score
        offset: 1
      - type: Destroy
        conditionals:
          []
  - type: Create
    target: star
    actions:
      - type: GravitousSet
        conditionals:
          []
        value: false
...
