---
name: win
friction: 0
maxXSpeed: -1
maxYSpeed: -1
gravitous: false
collidable: true
sprite: spr_win
xScale: 1
yScale: 1
animationSpeed: 0
depth: 0
attributes:
  {}
triggers:
  - type: Create
    target: win
    actions:
      - type: GravitousSet
        conditionals:
          []
        value: false
...
