---
name: ball
friction: 0.017
maxXSpeed: -1
maxYSpeed: -1
gravitous: true
collidable: true
sprite: spr_brick
xScale: 1
yScale: 1
animationSpeed: 0
depth: 0
attributes:
  {}
triggers:
  - type: Create
    target: ball
    actions:
      - type: MoveToNearest
        conditionals:
          []
        target: player
      - type: Move
        conditionals:
          []
        xOffset: 40
        yOffset: -40
...
