---
name: ball
friction: 0
maxXSpeed: -1
maxYSpeed: -1
gravitous: true
collidable: true
sprite: spr_brick
xScale: 1
yScale: 1
animationSpeed: 0
depth: 0
attributes:
  {}
triggers:
  - type: Timer
    index: 0
    actions:
      - type: Destroy
        conditionals:
          []
  - type: Create
    target: ball
    actions:
      - type: SetTimer
        conditionals:
          []
        index: 0
        time: 5
...
