---
name: greenball
friction: 0
maxXSpeed: -1
maxYSpeed: -1
gravitous: true
collidable: true
sprite: spr_greenball
xScale: 1
yScale: 1
animationSpeed: 0
depth: 0
attributes:
  {}
triggers:
  - type: Create
    target: greenball
    actions:
      - type: SetTimer
        conditionals:
          []
        index: 0
        time: 7.5
      - type: GravitousSet
        conditionals:
          []
        value: false
      - type: SetXSpeed
        conditionals:
          []
        speed: -1
  - type: Timer
    index: 0
    actions:
      - type: Destroy
        conditionals:
          []
  - type: Collision
    target: player
    actions:
      - type: Destroy
        conditionals:
          []
...
