---
name: player
friction: 0
maxXSpeed: 2
maxYSpeed: 10
gravitous: true
collidable: true
sprite: spr_player
xScale: 1
yScale: 1
animationSpeed: 0.025
depth: 0
attributes:
  touchingGround: 0
  jumpsLeft: 1
  random: 0
  invincible: 0
triggers:
  - type: ButtonInput
    id: 72
    state: down
    actions:
      - type: SetXSpeed
        conditionals:
          []
        speed: 0
  - type: Create
    target: player
    actions:
      - type: SetTimer
        conditionals:
          []
        index: 0
        time: 0.1
  - type: MouseInput
    state: down on
    actions:
      - type: MoveTo
        conditionals:
          []
        xPosition: 200
        yPosition: 200
      - type: SetXSpeed
        conditionals:
          []
        speed: 0
  - type: Collision
    target: wall
    actions:
      - type: AttributeSet
        conditionals:
          []
        attribute: jumpsLeft
        value: 1
      - type: PlaySound
        conditionals:
          - comparison: eq
            attribute: touchingGround
            value: 0
        name: test_sound
      - type: AttributeSet
        conditionals:
          []
        attribute: touchingGround
        value: 1
  - type: Collision
    target: bad_wall
    actions:
      - type: AttributeSet
        conditionals:
          []
        attribute: jumpsLeft
        value: 1
      - type: AttributeSet
        conditionals:
          []
        attribute: touchingGround
        value: 1
      - type: AttributeChange
        conditionals:
          - comparison: eq
            attribute: invincible
            value: 0
        attribute: lives
        offset: -1
      - type: Destroy
        conditionals:
          - comparison: le
            attribute: lives
            value: 0
      - type: SetTimer
        conditionals:
          - comparison: eq
            attribute: invincible
            value: 0
        index: 1
        time: 2
      - type: AttributeSet
        conditionals:
          []
        attribute: invincible
        value: 1
  - type: Collision
    target: ball
    actions:
      - type: AttributeSet
        conditionals:
          []
        attribute: jumpsLeft
        value: 1
      - type: PlaySound
        conditionals:
          - comparison: eq
            attribute: touchingGround
            value: 0
        name: test_sound
      - type: AttributeSet
        conditionals:
          []
        attribute: touchingGround
        value: 1
  - type: Timer
    index: 1
    actions:
      - type: AttributeSet
        conditionals:
          []
        attribute: invincible
        value: 0
  - type: Timer
    index: 0
    actions:
      - type: AttributeChange
        conditionals:
          []
        attribute: random
        offset: 1
      - type: AttributeSet
        conditionals:
          - comparison: ge
            attribute: random
            value: 10
        attribute: random
        value: 0
      - type: SetTimer
        conditionals:
          []
        index: 0
        time: 0.1
  - type: Collision
    target: fireball
    actions:
      - type: AttributeChange
        conditionals:
          - comparison: eq
            attribute: invincible
            value: 0
        attribute: lives
        offset: -1
      - type: Destroy
        conditionals:
          - comparison: le
            attribute: lives
            value: 0
      - type: SetTimer
        conditionals:
          - comparison: eq
            attribute: invincible
            value: 0
        index: 1
        time: 2
      - type: AttributeSet
        conditionals:
          []
        attribute: invincible
        value: 1
  - type: ButtonInput
    id: 3
    state: down
    actions:
      - type: SetXSpeed
        conditionals:
          []
        speed: 0
  - type: ButtonInput
    id: 3
    state: hold
    actions:
      - type: ApplyForce
        conditionals:
          []
        xAcceleration: 0.1
        yAcceleration: 0
  - type: ButtonInput
    id: 22
    state: down
    actions:
      - type: ApplyForce
        conditionals:
          - comparison: gt
            attribute: jumpsLeft
            value: 0
        xAcceleration: 0
        yAcceleration: -2
      - type: AttributeSet
        conditionals:
          - comparison: gt
            attribute: jumpsLeft
            value: 0
        attribute: touchingGround
        value: 0
      - type: AttributeChange
        conditionals:
          - comparison: gt
            attribute: jumpsLeft
            value: 0
        attribute: jumpsLeft
        offset: -1
  - type: ButtonInput
    id: 0
    state: hold
    actions:
      - type: ApplyForce
        conditionals:
          []
        xAcceleration: -0.1
        yAcceleration: 0
  - type: ButtonInput
    id: 0
    state: down
    actions:
      - type: SetXSpeed
        conditionals:
          []
        speed: 0
  - type: MouseInput
    state: down
    actions:
      - type: Create
        conditionals:
          - comparison: ge
            attribute: random
            value: 9
        target: bad_wall
        xPosition: 40
        yPosition: -100
      - type: Create
        conditionals:
          - comparison: lt
            attribute: random
            value: 9
        target: ball
        xPosition: 40
        yPosition: -100
  - type: Collision
    target: greenball
    actions:
      - type: AttributeChange
        conditionals:
          - comparison: eq
            attribute: invincible
            value: 0
        attribute: lives
        offset: -1
      - type: Destroy
        conditionals:
          - comparison: le
            attribute: lives
            value: 0
      - type: SetTimer
        conditionals:
          - comparison: eq
            attribute: invincible
            value: 0
        index: 1
        time: 2
      - type: AttributeSet
        conditionals:
          []
        attribute: invincible
        value: 1
...
