---
name: hud
friction: 0
maxXSpeed: -1
maxYSpeed: -1
gravitous: false
collidable: false
sprite: ~
xScale: 0
yScale: 0
animationSpeed: 0
depth: 0
attributes:
  {}
triggers:
  - type: ButtonInput
    id: 3
    state: hold
    actions:
      []
  - type: Draw
    target: hud
    actions:
      []
...
