---
name: hud
friction: 0
maxXSpeed: -1
maxYSpeed: -1
gravitous: false
collidable: false
sprite: ~
xScale: 0
yScale: 0
animationSpeed: 0
depth: 0
attributes:
  {}
triggers:
  - type: Create
    target: hud
    actions:
      - type: SetTimer
        conditionals:
          []
        index: 1
        time: 1
  - type: Timer
    index: 1
    actions:
      - type: PlaySound
        conditionals:
          []
        name: test_sound
      - type: SetTimer
        conditionals:
          []
        index: 1
        time: 1
...
